# Generated by Django 3.2.3 on 2021-05-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('colleges', models.CharField(max_length=200)),
                ('coursesMinerva', models.TextField(blank=True)),
                ('coursesElsewhere', models.TextField(blank=True)),
                ('overviewExpertise', models.TextField(blank=True)),
                ('expertiseKeywords', models.TextField(blank=True)),
                ('additionalInterest', models.TextField(blank=True)),
                ('links', models.TextField(blank=True)),
                ('coursesDomainExpertise', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentJunior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('collegeMajor', models.CharField(max_length=50)),
                ('primaryConc', models.CharField(max_length=100)),
                ('secondMajor', models.CharField(blank=True, max_length=50)),
                ('secondConc', models.CharField(blank=True, max_length=50)),
                ('customConc', models.CharField(blank=True, max_length=100)),
                ('minor', models.CharField(blank=True, max_length=50)),
                ('minorConc', models.CharField(blank=True, max_length=50)),
                ('knowledge2Offer', models.TextField(blank=True)),
                ('knowledge2Request', models.TextField(blank=True)),
                ('section', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('topProjectIdea', models.TextField()),
                ('degreeCommitment', models.CharField(max_length=100)),
                ('projectFeatures', models.TextField()),
                ('otherProjectIdeas', models.TextField(blank=True)),
                ('externalDependencies', models.TextField(blank=True)),
                ('hsrReview', models.TextField(blank=True)),
                ('relevantSkills', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
