# Generated by Django 3.2.3 on 2021-05-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSenior',
            new_name='StudentJunior',
        ),
    ]
